services:
  # Traefik Reverse Proxy Service (Edge Router)
  traefik:
    build:
      context: ./traefik
      dockerfile: .Dockerfile
      args:
        - TRAEFIK_VERSION=${TRAEFIK_VERSION}
        - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL}
        - TRAEFIK_PORT=${TRAEFIK_PORT}
        - TRAEFIK_API_PORT=${TRAEFIK_API_PORT}
        - TRAEFIK_API_ENTRYPOINT=${TRAEFIK_API_ENTRYPOINT}
        - TRAEFIK_DOCKER_NETWORK=${TRAEFIK_DOCKER_NETWORK}
        - TRAEFIK_EXPOSED_BY_DEFAULT=${TRAEFIK_EXPOSED_BY_DEFAULT}
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL}
      - TRAEFIK_PORT=${TRAEFIK_PORT}
      - TRAEFIK_API_PORT=${TRAEFIK_API_PORT}
      - TRAEFIK_API_ENTRYPOINT=${TRAEFIK_API_ENTRYPOINT}
      - TRAEFIK_DOCKER_NETWORK=${TRAEFIK_DOCKER_NETWORK}
      - TRAEFIK_EXPOSED_BY_DEFAULT=${TRAEFIK_EXPOSED_BY_DEFAULT}
      - TRAEFIK_CERT_EMAIL=${TRAEFIK_CERT_EMAIL}
      - DO_AUTH_TOKEN=${DO_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/var/log/traefik
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Nginx Web Server (Frontend + Static Assets)
  nginx:
    build:
      context: .
      dockerfile: ./nginx/.Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
        - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
        - NGINX_PORT=${NGINX_PORT}
        # React Build Args
        - REACT_APP_NODE_VERSION=${REACT_APP_NODE_VERSION}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
      - NGINX_PORT=${NGINX_PORT}
    labels:
      - "traefik.enable=true"
      # Frontend Routing
      - "traefik.http.routers.frontend.rule=Host(`${WEBSITE_DOMAIN}`) || Host(`www.${WEBSITE_DOMAIN}`) || Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=${NGINX_PORT}"
      # HTTP -> HTTPS Redirect
      - "traefik.http.routers.frontend-http.rule=Host(`${WEBSITE_DOMAIN}`) || Host(`www.${WEBSITE_DOMAIN}`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Security Headers
      - "traefik.http.middlewares.security-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.security-headers.headers.stsseconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stspreload=true"
      - "traefik.http.middlewares.security-headers.headers.framedeny=true"
      - "traefik.http.middlewares.security-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserxssfilter=true"
      # Apply Headers to Frontend
      - "traefik.http.routers.frontend.middlewares=security-headers"
    ports:
      - "${NGINX_HOST_PORT:-8080}:${NGINX_PORT:-80}"
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:${NGINX_PORT}/health']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile
      args:
        - NODE_VERSION=${BACKEND_NODE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
    labels:
      - "traefik.enable=true"
      # API Routing (/api)
      - "traefik.http.routers.api.rule=(Host(`${WEBSITE_DOMAIN}`) || Host(`www.${WEBSITE_DOMAIN}`) || Host(`localhost`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=security-headers"
      - "traefik.http.services.api.loadbalancer.server.port=${BACKEND_PORT}"
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    networks:
      - base2_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:${BACKEND_PORT}/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # PostgreSQL Database Service
  postgres:
    build:
      context: ./postgres
      dockerfile: .Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # pgAdmin Database Management Service
  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: .Dockerfile
      args:
        - PGADMIN_VERSION=${PGADMIN_VERSION}
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - base2_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # No ports exposed exposed to host. Not routed via Traefik for now (internal use only).
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${PGADMIN_PORT}/misc/ping',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Application Monitoring (Uptime Kuma)
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: ${COMPOSE_PROJECT_NAME}_uptime_kuma
    volumes:
      - uptime_kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`status.${WEBSITE_DOMAIN}`)"
      - "traefik.http.routers.uptime.entrypoints=web-secure"
      - "traefik.http.routers.uptime.tls.certresolver=letsencrypt"
      - "traefik.http.routers.uptime.middlewares=security-headers"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
    networks:
      - base2_network
    restart: unless-stopped

# Networks Configuration
networks:
  base2_network:
    name: ${NETWORK_NAME}
    driver: bridge

# Volumes Configuration
volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
    driver: local

  pgadmin_data:
    name: ${COMPOSE_PROJECT_NAME}_pgadmin_data
    driver: local

  traefik_logs:
    name: ${COMPOSE_PROJECT_NAME}_traefik_logs
    driver: local

  uptime_kuma_data:
    name: ${COMPOSE_PROJECT_NAME}_uptime_kuma_data
    driver: local
